language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t pankajnalin/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true pankajnalin/react-test npm test -- --coverage

after_success:
  - docker build -t pankajnalin/multi-client ./client
  - docker build -t pankajnalin/multi-nginx ./nginx
  - docker build -t pankajnalin/multi-server ./server
  - docker build -t pankajnalin/multi-worker ./worker 
  #log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  #Must do docker logout and docker login in terminal before pushing to docker hub
  - docker push pankajnalin/multi-client
  - docker push pankajnalin/multi-nginx
  - docker push pankajnalin/multi-server
  - docker push pankajnalin/multi-worker